# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cfa70ccc4038e80a64878b2d0f0bfddc35e263fe9a2c89890659809976f0b22aa9b1f88b3a4f2908ebf2a77397fe09e6644bab32796def6dd2b7a61b19af24

test:
  secret_key_base: b9d61ace8ec503dc08bd7516adde0506b2aa3a2e0a691f1a581d31ef50cf02b8336881f32db763065afa05cc0376992ef383de5d70a02ccc52f50ea562084417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
